In [1]:
# Upload the local SQLite database or dataset file (e.g., movies.sqlite) to use in Colab
from google.colab import files
uploaded = files.upload()

Saving movie.sqlite to movie.sqlite

In [2]:
# Required python libraries
import pandas as pd
import sqlite3

In [6]:
# Establish a connection to the uploaded SQLite database
conn = sqlite3.connect("movie.sqlite")
# create a cursor for executing SQL queries
cur = conn.cursor()

Get all the data about the movies

In [46]:
# Fetching all the data about the movies
cur.execute("SELECT name FROM sqlite_master WHERE type='table'")
tables = cur.fetchall()
# Displaying all the data about the movies
tables

[('movies',), ('sqlite_sequence',), ('directors',)]

In [66]:
# Establishig conncetion
cur.execute("SELECT * FROM movies;")
# creating cursor object
movies_table = cur.fetchall()
# displaying database
movies_table[4]

(43601,
 'John Carter',
 260000000,
 43,
 '2012-03-07',
 284139100,
 'John Carter',
 6.1,
 2124,
 "John Carter is a war-weary, former military captain who's inexplicably transported to the mysterious and exotic planet of Barsoom (Mars) and reluctantly becomes embroiled in an epic conflict. It's a world on the brink of collapse, and Carter rediscovers his humanity when he realizes the survival of Barsoom and its people rests in his hands.",
 'Lost in our world, found in another.',
 49529,
 4766)

In [72]:
#Creating dataframe
movies=pd.DataFrame(movies_table,columns=['id','original_title','budget','popularity','release_date','revenue','title','vote_average','vote_count','overview','tagline','uid','director_id'])

In [75]:
# displaying dataframe
movies[:6]

,id,original_title,budget,popularity,release_date,revenue,title,vote_average,vote_count,overview,tagline,uid,director_id
0,43597,Avatar,237000000,150,2009-12-10,2787965087,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,19995,4762
1,43598,Pirates of the Caribbean: At World's End,300000000,139,2007-05-19,961000000,Pirates of the Caribbean: At World's End,6.9,4500,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",285,4763
2,43599,Spectre,245000000,107,2015-10-26,880674609,Spectre,6.3,4466,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,206647,4764
3,43600,The Dark Knight Rises,250000000,112,2012-07-16,1084939099,The Dark Knight Rises,7.6,9106,Following the death of District Attorney Harve...,The Legend Ends,49026,4765
4,43601,John Carter,260000000,43,2012-03-07,284139100,John Carter,6.1,2124,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.",49529,4766
5,43602,Spider-Man 3,258000000,115,2007-05-01,890871626,Spider-Man 3,5.9,3576,The seemingly invincible Spider-Man goes up ag...,The battle within.,559,4767

In [12]:
#displaying info of movies table
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4773 entries, 0 to 4772
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              4773 non-null   int64
 1   original_title  4773 non-null   object
 2   budget          4773 non-null   int64
 3   popularity      4773 non-null   int64
 4   release_date    4773 non-null   object
 5   revenue         4773 non-null   int64
 6   title           4773 non-null   object
 7   vote_average    4773 non-null   float64
 8   vote_count      4773 non-null   int64
 9   overview        4770 non-null   object
 10  tagline         3951 non-null   object
 11  uid             4773 non-null   int64
 12  director_id     4773 non-null   int64
dtypes: float64(1), int64(7), object(5)
memory usage: 484.9+ KB

In [27]:
# Displaying directors table
cur.execute("select * from directors")
directors_table = cur.fetchall()

Get top 6 directors data

In [69]:
directors_table[:6]

[('James Cameron', 4762, 2, 2710, 'Directing'),
 ('Gore Verbinski', 4763, 2, 1704, 'Directing'),
 ('Sam Mendes', 4764, 2, 39, 'Directing'),
 ('Christopher Nolan', 4765, 2, 525, 'Directing'),
 ('Andrew Stanton', 4766, 2, 7, 'Directing'),
 ('Sam Raimi', 4767, 2, 7623, 'Directing')]

In [32]:
# Displaying directors Data Frame
directors = pd.DataFrame(directors_table,columns=['name','id','gender','uid','department'])
directors

                   name    id  gender      uid department
0         James Cameron  4762       2     2710  Directing
1        Gore Verbinski  4763       2     1704  Directing
2            Sam Mendes  4764       2       39  Directing
3     Christopher Nolan  4765       2      525  Directing
4        Andrew Stanton  4766       2        7  Directing
...                 ...   ...     ...      ...        ...
2344      Shane Carruth  7106       2    76624  Directing
2345   Neill Dela Llana  7107       0  1174437  Directing
2346        Scott Smith  7108       0  1219158  Directing
2347        Daniel Hsia  7109       2   208138  Directing
2348   Brian Herzlinger  7110       2    85563  Directing

[2349 rows x 5 columns]

In [34]:
# Diaplaying directors table info
directors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2349 entries, 0 to 2348
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        2349 non-null   object
 1   id          2349 non-null   int64
 2   gender      2349 non-null   int64
 3   uid         2349 non-null   int64
 4   department  2349 non-null   object
dtypes: int64(3), object(2)
memory usage: 91.9+ KB

Check how many movies are present in IMDB table?

In [35]:
# Fetching the number of movies
cur.execute("SELECT COUNT(title) FROM movies")
count=cur.fetchall()
# Displaying the number of movies
print(f"The no. of movies present in the IMDB database id {count[0]}")

The no. of movies present in the IMDB database id (4773,)

Find these 3 directors: james caneron,Luc Besson, Jhon Woo?

In [36]:
# Fetching the Specified movies
cur.execute("SELECT * FROM DIRECTORS WHERE name IN ('James Cameron','Luc Besson','John Woo')")
three_directors=cur.fetchall()

In [37]:
# Displaying the Specified movies
print(f"These 3 directors are:{three_directors}")

These 3 directors are:[('James Cameron', 4762, 2, 2710, 'Directing'), ('John Woo', 4893, 2, 11401, 'Directing'), ('Luc Besson', 4949, 2, 59, 'Directing')]

Find all the directors with name starting with 'Steven'?

In [38]:
# Fetching all the directors with name starting with 'Steven'
cur.execute("SELECT * FROM directors WHERE name LIKE 'Steven%'")
name_like = cur.fetchall()
# Displaying all the directors with name starting with 'Steven'
print(f"The directors whose names are starting with the word 'Steven' are {name_like}")

The directors whose names are starting with the word 'Steven' are [('Steven Spielberg', 4799, 2, 488, 'Directing'), ('Steven Soderbergh', 4909, 2, 1884, 'Directing'), ('Steven Brill', 5013, 2, 32593, 'Directing'), ('Steven Zaillian', 5117, 2, 2260, 'Directing'), ('Steven Quale', 5216, 2, 93214, 'Directing'), ('Steven Seagal', 5221, 2, 23880, 'Directing'), ('Steven E. de Souza', 5390, 2, 1726, 'Directing'), ('Steven Shainberg', 5803, 2, 67795, 'Directing'), ('Steven R. Monroe', 6713, 2, 88039, 'Directing')]

Count the female directors?

In [39]:
# Fetchinh the female directors
cur.execute("SELECT COUNT(gender) FROM directors WHERE gender == '1'")
females = cur.fetchall()
# Displaying the female directors
print(f"The number of female directors are {females[0][0]}")

The number of female directors are 150

Find the name of the 10th first women director?

In [40]:
# Fetching the name of the 10th first women director
cur.execute("SELECT name FROM directors WHERE gender == '1'")
tenth_female = cur.fetchall()
# Displaying the name of the 10th first women director
print(f"The 10th 1st women is {tenth_female[9][0]}")

The 10th 1st women is Angelina Jolie

What are the 3 most popular movies?

In [43]:
# Fetching the 3 most popular movies
cur.execute("SELECT title FROM movies ORDER BY POPULARITY DESC LIMIT 3")
most_popular = cur.fetchall()
# Displaying the 3 most popular movies
print(f"The 3 most popular movies are {most_popular[0][0]}, {most_popular[1][0]}, {most_popular[2][0]}")

The 3 most popular movies are Minions, Interstellar, Deadpool

What are the 3 most bankable movies?

In [44]:
# Fetching the 3 most bankable movies
cur.execute("SELECT Original_title FROM movies order by budget DESC LIMIT 3")
most_bankable = cur.fetchall()
# Displaying the 3 most bankable movies
print(f"The 3 most bankable movies are {most_bankable[0][0]}, {most_bankable[1][0]}, {most_bankable[2][0]}")

The 3 most bankable movies are Pirates of the Caribbean: On Stranger Tides, Pirates of the Caribbean: At World's End, Avengers: Age of Ultron

What is the most awarded average rated movie since the Jan 1st, 2000?

In [48]:
# Fetching the most awarded average rated movie since the Jan 1st, 2000
cur.execute("SELECT title FROM movies WHERE Release_date > '2000-01-01' ORDER BY vote_average DESC LIMIT 1")
most_awarded = cur.fetchall()
# Displaying the most awarded average rated movie since the Jan 1st, 2000
print(f"The most awarded average rated movie is {most_awarded[0][0]}")

The most awarded average rated movie is Sardaarji

which movie(s) were directed by Brenda Chapman?

....

In [50]:
# Fetching the movie(s) were directed by Brenda Chapman
cur.execute("SELECT m.original_title FROM movies AS m JOIN directors AS d ON m.director_id == d.id WHERE d.name LIKE 'Brenda Chapman'")
directed_by = cur.fetchall()
# Displaying the movie(s) were directed by Brenda Chapman
print(f"The movie(s) directed by Brenda Chapman is {directed_by[0][0]}")

The movie(s) directed by Brenda Chapman is Brave

Find the director who made most movies?

In [53]:
#Fetching the director who made most movies
cur.execute("SELECT d.name FROM MOVIES AS m JOIN directors AS d ON m.director_id == d.id GROUP BY m.director_id ORDER BY COUNT(m.title) DESC LIMIT 1")
most_movies = cur.fetchall()
# Displaying the director who made most movies
print(f"The director who made the most movies is '{most_movies[0][0]}'")

The director who made the most movies is 'Steven Spielberg'

Name of the director who is most bankable?

In [54]:
# Fetching the name of the director who is most bankable
cur.execute("SELECT d.name FROM movies as m JOIN directors as d ON m.director_id == d.id GROUP BY director_id ORDER BY SUM(m.budget) DESC LIMIT 1")
most_bankable = cur.fetchall()
# Displaying the name of the director who is most bankable
print(f"The most bankable director is {most_bankable[0][0]}")

The most bankable director is Steven Spielberg

Budget Analysis

Tell the Top 10 highest budget making movies

In [55]:
# Displaying the Top 10 highest budget making movies
top_10 = pd.DataFrame(cur.execute("SELECT * FROM movies ORDER BY budget DESC LIMIT 10"),columns = ['id', 'original_title', 'budget', 'popularity', 'release_date',
       'revenue', 'title', 'vote_average', 'vote_count', 'overview', 'tagline',
       'uid', 'director_id'])
# Displaying the data frame of the Top 10 highest budget making movies
top_10

,id,original_title,budget,popularity,release_date,revenue,title,vote_average,vote_count,overview,tagline,uid,director_id
0,43614,Pirates of the Caribbean: On Stranger Tides,380000000,135,2011-05-14,1045713802,Pirates of the Caribbean: On Stranger Tides,6.4,4948,Captain Jack Sparrow crosses paths with a woma...,Live Forever Or Die Trying.,1865,4775
1,43598,Pirates of the Caribbean: At World's End,300000000,139,2007-05-19,961000000,Pirates of the Caribbean: At World's End,6.9,4500,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",285,4763
2,43604,Avengers: Age of Ultron,280000000,134,2015-04-22,1405403694,Avengers: Age of Ultron,7.3,6767,When Tony Stark tries to jumpstart a dormant p...,A New Age Has Come.,99861,4769
3,43607,Superman Returns,270000000,57,2006-06-28,391081192,Superman Returns,5.4,1400,Superman returns to discover his 5-year absenc...,None,1452,4772
4,43601,John Carter,260000000,43,2012-03-07,284139100,John Carter,6.1,2124,"John Carter is a war-weary, former military ca...","Lost in our world, found in another.",49529,4766
5,43603,Tangled,260000000,48,2010-11-24,591794936,Tangled,7.4,3330,When the kingdom's most wanted-and most charmi...,They're taking adventure to new lengths.,38757,4768
6,43602,Spider-Man 3,258000000,115,2007-05-01,890871626,Spider-Man 3,5.9,3576,The seemingly invincible Spider-Man goes up ag...,The battle within.,559,4767
7,43610,The Lone Ranger,255000000,49,2013-07-03,89289910,The Lone Ranger,5.9,2311,The Texas Rangers chase down a gang of outlaws...,Never Take Off the Mask,57201,4763
8,43600,The Dark Knight Rises,250000000,112,2012-07-16,1084939099,The Dark Knight Rises,7.6,9106,Following the death of District Attorney Harve...,The Legend Ends,49026,4765
9,43605,Harry Potter and the Half-Blood Prince,250000000,98,2009-07-07,933959197,Harry Potter and the Half-Blood Prince,7.4,5293,"As Harry begins his sixth year at Hogwarts, he...",Dark Secrets Revealed,767,4770

Revenue Analysis

Find top 10 revenue making movies?

In [56]:
# Fetching the top 10 revenue making movies
cur.execute("SELECT * FROM movies ORDER BY revenue DESC LIMIT 10")
top10_movies = cur.fetchall()
most_revenue = pd.DataFrame(top10_movies,columns = ['id', 'original_title', 'budget', 'popularity', 'release_date',
       'revenue', 'title', 'vote_average', 'vote_count', 'overview', 'tagline',
       'uid', 'director_id'])
# Displaying the top 10 revenue making movies
most_revenue

,id,original_title,budget,popularity,release_date,revenue,title,vote_average,vote_count,overview,tagline,uid,director_id
0,43597,Avatar,237000000,150,2009-12-10,2787965087,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,19995,4762
1,43622,Titanic,200000000,100,1997-11-18,1845034188,Titanic,7.5,7562,"84 years later, a 101-year-old woman named Ros...",Nothing on Earth could come between them.,597,4762
2,43613,The Avengers,220000000,144,2012-04-25,1519557910,The Avengers,7.4,11776,When an unexpected enemy emerges and threatens...,Some assembly required.,24428,4769
3,43625,Jurassic World,150000000,418,2015-06-09,1513528810,Jurassic World,6.5,8662,Twenty-two years after the events of Jurassic ...,The park is open.,135397,4783
4,43641,Furious 7,190000000,102,2015-04-01,1506249360,Furious 7,7.3,4176,Deckard Shaw seeks revenge against Dominic Tor...,Vengeance Hits Home,168259,4794
5,43604,Avengers: Age of Ultron,280000000,134,2015-04-22,1405403694,Avengers: Age of Ultron,7.3,6767,When Tony Stark tries to jumpstart a dormant p...,A New Age Has Come.,99861,4769
6,43721,Frozen,150000000,165,2013-11-27,1274219009,Frozen,7.3,5295,Young princess Anna of Arendelle dreams about ...,Only the act of true love will thaw a frozen h...,109445,4844
7,43628,Iron Man 3,200000000,77,2013-04-18,1215439994,Iron Man 3,6.8,8806,When Tony Stark's world is torn apart by a for...,Unleash the power behind the armor.,68721,4784
8,44143,Minions,74000000,875,2015-06-17,1156730962,Minions,6.4,4571,"Minions Stuart, Kevin and Bob are recruited by...","Before Gru, they had a history of bad bosses",211672,5045
9,43623,Captain America: Civil War,250000000,198,2016-04-27,1153304495,Captain America: Civil War,7.1,7241,"Following the events of Age of Ultron, the col...",Divided We Fall,271110,4781

Voting Analysis

Find the most popular movies with highest vote_average?

In [58]:
# Fetching the most popular movies with highest vote_average
cur.execute("SELECT * FROM movies ORDER BY vote_average DESC LIMIT 10")
most_popular = cur.fetchall()
popular_movie = pd.DataFrame(most_popular,columns = ['id', 'original_title', 'budget', 'popularity', 'release_date',
       'revenue', 'title', 'vote_average', 'vote_count', 'overview', 'tagline',
       'uid', 'director_id'])
# Displaying the data frame of most popular movies with highest vote_average
popular_movie

,id,original_title,budget,popularity,release_date,revenue,title,vote_average,vote_count,overview,tagline,uid,director_id
0,47116,Stiff Upper Lips,0,0,1998-06-12,0,Stiff Upper Lips,10.0,1,Stiff Upper Lips is a broad parody of British ...,None,89861,6332
1,47642,"Dancer, Texas Pop. 81",0,0,1998-05-01,565592,"Dancer, Texas Pop. 81",10.0,1,"Four guys, best friends, have grown up togethe...",in the middle of nowhere they had everything,78373,5463
2,47589,Sardaarji,0,0,2015-06-26,0,Sardaarji,9.5,2,A ghost hunter uses bottles to capture trouble...,None,346081,6588
3,45983,One Man's Hero,0,0,1999-08-02,0,One Man's Hero,9.3,2,One Man's Hero tells the little-known story of...,One man's hero is another man's traitor.,69848,5770
4,45478,The Shawshank Redemption,25000000,136,1994-09-23,28341469,The Shawshank Redemption,8.5,8205,Framed in the 1940s for the double murder of h...,Fear can hold you prisoner. Hope can set you f...,278,5051
5,46567,There Goes My Baby,10500000,0,1994-09-02,123509,There Goes My Baby,8.5,2,A group of high school seniors meets in the su...,None,88641,6051
6,46393,The Prisoner of Zenda,0,4,1937-09-03,0,The Prisoner of Zenda,8.4,11,An Englishman on a Ruritarian holiday must imp...,The most thrilling swordfight ever filmed...,43867,5972
7,46934,The Godfather,6000000,143,1972-03-14,245066411,The Godfather,8.4,5893,"Spanning the years 1945 to 1955, a chronicle o...",An offer you can't refuse.,238,5179
8,44259,Fight Club,63000000,146,1999-10-15,100853753,Fight Club,8.3,9413,A ticking-time-bomb insomniac and a slippery s...,Mischief. Mayhem. Soap.,550,4829
9,45415,Schindler's List,22000000,104,1993-11-29,321365567,Schindler's List,8.3,4329,The true story of how businessman Oskar Schind...,"Whoever saves one life, saves the world entire.",424,4799

Director Analysis

Find all the directors with the number of movies and revenue?

In [59]:
# Fetching all the directors with the number of movies and revenue
cur.execute("SELECT d.name, COUNT(*) AS 'Total Movies',SUM(revenue) AS revenue FROM movies AS m JOIN directors AS d ON m.director_id == d.id GROUP BY director_id")
director_revenue = cur.fetchall()
# Displaying the data frame of all the directors with the number of movies and revenue
director_most_revenue = pd.DataFrame(director_revenue,columns=['Director Name','Total Movies','revenue'])
director_most_revenue

          Director Name  Total Movies     revenue
0         James Cameron             7  5883569439
1        Gore Verbinski             7  3177013357
2            Sam Mendes             7  2713548809
3     Christopher Nolan             8  4227483234
4        Andrew Stanton             4  2109045355
...                 ...           ...         ...
2344      Shane Carruth             1      424760
2345   Neill Dela Llana             1           0
2346        Scott Smith             1           0
2347        Daniel Hsia             1           0
2348   Brian Herzlinger             1           0

[2349 rows x 3 columns]

Find all the directors with the number of movies and revenue where the no. of movies should be taken into account for doing analysis.The director who has highest no. of movies should comes at the top and so on and so forth?

In [60]:
# Fetching the director who has highest no. of movies should comes at the top
cur.execute("SELECT d.name, COUNT(m.title) AS 'Total Movies', SUM(m.revenue) AS revenue FROM movies AS m JOIN directors AS d ON m.director_id == d.id GROUP BY director_id ORDER BY COUNT(m.title) DESC LIMIT 10")
director_revenue = cur.fetchall()
# Displaying the data frame of the director who has highest no. of movies should comes at the top
director_most_revenue = pd.DataFrame(director_revenue,columns=['Director Name','Total Movies','revenue'])
director_most_revenue

       Director Name  Total Movies     revenue
0   Steven Spielberg            27  9147393164
1        Woody Allen            21   669101038
2     Clint Eastwood            20  2512058888
3    Martin Scorsese            20  1956635998
4          Spike Lee            16   340618771
5   Robert Rodriguez            16  1109899581
6       Ridley Scott            16  3189557997
7       Renny Harlin            15  1031500590
8  Steven Soderbergh            15  2114864443
9       Oliver Stone            14  1278048615

Give the title of the movies, release_date,budget,revenue, popularity, vote_average made by Stevel Spielberg?

In [76]:
# Fetching the title of the movies, release_date,budget,revenue, popularity, vote_average made by Stevel Spielberg
cur.execute("SELECT m.title, m.release_date, m.budget, m.revenue, m.popularity, m.vote_average FROM movies AS m JOIN directors AS d ON m.director_id == d.id WHERE d.name == 'Steven Spielberg'")
movies = cur.fetchall()
# Displaying the title of the movies, release_date,budget,revenue, popularity, vote_average made by Stevel Spielberg
movies_list_Stevel_Spielberg = pd.DataFrame(movies,columns=['Movie Name','release_date', 'budget', 'revenue', 'popularity', 'vote_average'])
movies_list_Stevel_Spielberg[:6]

,Movie Name,release_date,budget,revenue,popularity,vote_average
0,Indiana Jones and the Kingdom of the Crystal S...,2008-05-21,185000000,786636033,75,5.7
1,The BFG,2016-06-01,140000000,183345589,44,6.0
2,War of the Worlds,2005-06-28,132000000,591739379,48,6.2
3,The Adventures of Tintin,2011-10-25,130000000,371940071,89,6.7
4,Minority Report,2002-06-20,102000000,358372926,65,7.1
5,A.I. Artificial Intelligence,2001-06-29,100000000,235926552,34,6.8